"""SQLite storage, migrations, run records, and view cache helpers."""

from radar.core.storage.db import applied_migrations, migrate, migrate_market_db, migrate_message_db
from radar.core.storage.runs import (
    RunRecord,
    RunStatus,
    cancel_run,
    fail_run,
    fail_stale_runs,
    finish_run,
    get_run,
    get_running_run,
    is_run_running,
    list_runs,
    start_run,
    update_run_progress,
)
from radar.core.storage.store import (
    classified_message_ids,
    connect,
    fetch_window_covered,
    fetch_window_exists,
    init_db,
    list_messages_for_classification,
    record_fetch_window,
    upsert_message_classifications,
    upsert_messages,
)
from radar.core.storage.view_cache import (
    cache_key,
    cached_model,
    cleanup_cache,
    dashboard_dependency_key,
    load_model,
    store_model,
)

__all__ = [
    "RunRecord",
    "RunStatus",
    "applied_migrations",
    "cache_key",
    "cached_model",
    "cancel_run",
    "classified_message_ids",
    "cleanup_cache",
    "connect",
    "dashboard_dependency_key",
    "fail_run",
    "fail_stale_runs",
    "fetch_window_covered",
    "fetch_window_exists",
    "finish_run",
    "get_run",
    "get_running_run",
    "init_db",
    "is_run_running",
    "list_messages_for_classification",
    "list_runs",
    "load_model",
    "migrate",
    "migrate_market_db",
    "migrate_message_db",
    "record_fetch_window",
    "start_run",
    "store_model",
    "update_run_progress",
    "upsert_message_classifications",
    "upsert_messages",
]
