"""SQLite storage, migrations, and run record helpers."""

from radar.core.storage.db import (
    applied_migrations,
    migrate,
    migrate_market_db,
    migrate_message_db,
    migrate_report_db,
    migrate_valuation_db,
)
from radar.core.storage.runs import (
    RunRecord,
    RunStatus,
    cancel_run,
    fail_run,
    fail_stale_runs,
    finish_run,
    get_run,
    get_running_run,
    is_run_running,
    list_runs,
    start_run,
    update_run_progress,
)
from radar.core.storage.store import (
    connect,
    connect_readonly,
    fetch_window_covered,
    fetch_window_exists,
    init_db,
    record_fetch_window,
    upsert_messages,
)

__all__ = [
    "RunRecord",
    "RunStatus",
    "applied_migrations",
    "cancel_run",
    "connect",
    "connect_readonly",
    "fail_run",
    "fail_stale_runs",
    "fetch_window_covered",
    "fetch_window_exists",
    "finish_run",
    "get_run",
    "get_running_run",
    "init_db",
    "is_run_running",
    "list_runs",
    "migrate",
    "migrate_market_db",
    "migrate_message_db",
    "migrate_report_db",
    "migrate_valuation_db",
    "record_fetch_window",
    "start_run",
    "update_run_progress",
    "upsert_messages",
]
