"""LLM protocol clients shared by future CLI/Web use cases."""

from radar.core.llm.client import (
    ChatMessage,
    LlmChatDelta,
    LlmChatDone,
    LlmChatResponse,
    LlmChatStreamEvent,
    LlmConfigError,
    LlmReasoningDelta,
    LlmToolCall,
    LlmToolCallDelta,
    LlmToolCallDone,
    LlmToolCallStarted,
    LlmToolSpec,
    RuntimeLlmProvider,
    chat,
    chat_json,
    chat_json_list,
    chat_response,
    resolve_provider,
    stream_chat_response,
)

__all__ = [
    "ChatMessage",
    "LlmChatDelta",
    "LlmChatDone",
    "LlmChatResponse",
    "LlmChatStreamEvent",
    "LlmConfigError",
    "LlmReasoningDelta",
    "LlmToolCall",
    "LlmToolCallDelta",
    "LlmToolCallDone",
    "LlmToolCallStarted",
    "LlmToolSpec",
    "RuntimeLlmProvider",
    "chat",
    "chat_json",
    "chat_json_list",
    "chat_response",
    "resolve_provider",
    "stream_chat_response",
]
